---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.baseName }}
  namespace: {{ .Values.baseName }}
  labels:
    app: {{ .Values.baseName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.baseName }}
  template:
    metadata:
      labels:
        app: {{ .Values.baseName }}
    spec:
      containers:
      - name: {{ .Values.baseName }}
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        {{ if .Values.command }}
        command:
{{ toYaml .Values.command | indent 8 }}
        {{- end }}
        volumeMounts:
        - readOnly: true
          mountPath: /var/ssl
          name: server-certs
        - readOnly: true
          mountPath: /etc/nginx/http.d
          name: webserver-config
        readinessProbe:
          httpGet:
            path: /health
            scheme: HTTPS
            port: 8443
          intialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            scheme: HTTPS
            port: 8443
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: server-certs
        secret:
          secretName: {{ .Values.baseName }}-server-cert
      - name: webserver-config
        configMap:
          name: {{ .Values.baseName }}-webserver-config
...

