---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Values.baseName }}
webhooks:
- name: {{ .Values.baseName }}.{{ .Values.baseName }}.svc
  failurePolicy: Ignore
  sideEffects: NoneOnDryRun
  timeoutSeconds: 5
  admissionReviewVersions:
  - v1
  rules:
  - operations:
    - CREATE
    - DELETE
    - UPDATE
    apiGroups:
    - "*"
    apiVersions:
    - v1
    resources:
    - pods
    scope: Namespaced
  clientConfig:
    caBundle: {{ .Values.caCertBundleB64 }}
    service:
      namespace: {{ .Values.baseName }}
      name: {{ .Values.baseName }}
      path: /validate
...
